GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJ5IiwiaWF0IjoxNzUzNDE3NTM0LCJleHAiOjE3NTM0MTgxMzR9.Jq-HxjKl2mLVXR8OTNhyWrYaAJsyOGw5bxKProzxUTE

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Harry" 
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJ5IiwiaWF0IjoxNzUzNDE3NTM0LCJleHAiOjE3NTQwMjIzMzR9.zMvXfsclwdho-Z_Gyv71idTuuGYhv2v0gKhD3xkl57Q"
}

###
DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJ5IiwiaWF0IjoxNzUzNDE3NTM0LCJleHAiOjE3NTQwMjIzMzR9.zMvXfsclwdho-Z_Gyv71idTuuGYhv2v0gKhD3xkl57Q"
}
