GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJ5IiwiaWF0IjoxNzUzNDI0MjM2LCJleHAiOjE3NTM0MjQ4MzZ9.Hv0umtDC3WB_5eNpPw5CNj4cY9T1kJSLXyUupzguShs

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Harry" 
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJ5IiwiaWF0IjoxNzUzNDI0MjM2LCJleHAiOjE3NTQwMjkwMzZ9.arRdt9me4GuBKlp4l_hz_IC2690yJtSu3OdXIhzzUHo"
}

###
DELETE http://localhost:3000/logout
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJ5IiwiaWF0IjoxNzUzNDI0MjM2LCJleHAiOjE3NTM0MjQ4MzZ9.Hv0umtDC3WB_5eNpPw5CNj4cY9T1kJSLXyUupzguShs",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhhcnJ5IiwiaWF0IjoxNzUzNDI0MjM2LCJleHAiOjE3NTQwMjkwMzZ9.arRdt9me4GuBKlp4l_hz_IC2690yJtSu3OdXIhzzUHo"
}
